name: framemobile
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.1
  curved_navigation_bar: ^1.0.6
  http: ^1.3.0
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.4
  random_string: ^2.3.1
  image_picker: ^1.1.2
  permission_handler: ^11.4.0
  fluttertoast: ^8.2.12
  firebase_storage: ^12.4.3
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0   
  image_gallery_saver_plus: ^3.0.5  # ✅ Using correct version from pub.dev

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "images/icons/wallpapericon.png"  # Single path for both Android and iOS

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/icons/wallpapericon.png
